Repository cityofaustin/joplin, pull requests merged in 2019-11, with the labels that each got.

#446 fix redirect to search home page
  joplin/base/views/joplin_search_views.py
  joplin/settings.py
Labels: PR: reviewed-approved

#447 Master -> Prod:: Search Page fix
  joplin/base/views/joplin_search_views.py
  joplin/settings.py
Labels: PR: unreviewed

#445 3163 guide pages are not español friendly
  README.md
  README/images.md
  joplin/api/schema.py
Labels: PR: unreviewed

#449 3146 - get unpublish back on the edit page
  joplin/templates/wagtailadmin/pages/edit.html
Labels: PR: reviewed-approved

#452 Master -> Prod
  README.md
  README/images.md
  joplin/api/schema.py
  joplin/templates/wagtailadmin/pages/edit.html
  joplin/templates/wagtailadmin/shared/field.html
Labels: PR: unreviewed

#448 3363 Main search alert & styling fixes
  joplin/base/views/joplin_search_views.py
  joplin/css/layouts/headers.scss
  joplin/templates/wagtailadmin/pages/search_header.html
  joplin/templates/wagtailadmin/shared/field.html
Labels: PR: reviewed-approved, bug

#453 2861 forgot it
  README.md
  joplin/templates/wagtailadmin/login.html
Labels: PR: reviewed-approved

#457 should do the trick for now
  joplin/base/views/joplin_views.py
Labels: PR: unreviewed

#455 3244-guide-icon-tiles
  joplin/api/schema.py
Labels: PR: reviewed-approved

#456 Is this good enough?
  joplin/templates/wagtailadmin/chooser/browse.html
Labels: PR: reviewed-approved

#450 3348 signals
  joplin/base/apps.py
  joplin/base/signals/aws_publish.py
  joplin/base/signals/janis_build_triggers.py
  joplin/base/signals/netlify_publish.py
Labels: PR: reviewed-approved

#460 try fixing it
  joplin/settings.py
Labels: PR: unreviewed

#462 3120 remove ordered lists from service steps
  joplin/base/models/service_page.py
Labels: PR: reviewed-approved

#461 3371 - Add embed to WYSIWYG_GENERAL
  joplin/base/models/__init__.py
  joplin/base/models/constants.py
Labels: PR: reviewed-approved

#466 Master -> Prod
  joplin/base/models/__init__.py
  joplin/base/models/constants.py
  joplin/base/models/service_page.py
Labels: PR: unreviewed

#465 3396 dummy data
  README.md
  docker-compose.local_override.yml
  docker-compose.migration_test_override.yml
  docker-entrypoint.sh
  joplin/db/system-generated/dummy.datadump.json
  joplin/db/system-generated/dummy_datadump_metadata.txt
  scripts/migration-test.sh
Labels: PR: unreviewed

#470 add 'ol' back
  joplin/base/models/service_page.py
Labels: PR: unreviewed

#471 Master ---> Prod
  README.md
  docker-compose.local_override.yml
  docker-compose.migration_test_override.yml
  docker-entrypoint.sh
  joplin/base/models/service_page.py
  joplin/db/system-generated/dummy.datadump.json
  joplin/db/system-generated/dummy_datadump_metadata.txt
  scripts/migration-test.sh
Labels: PR: unreviewed

#472 3481 - step lists
  joplin/base/models/service_page.py
Labels: PR: unreviewed

#473 ols back
  joplin/base/models/service_page.py
Labels: PR: unreviewed

#474 master -> prod
  joplin/base/models/service_page.py
Labels: PR: unreviewed

#476 remove ols
  joplin/base/models/service_page.py
Labels: PR: unreviewed
