Repository cityofaustin/joplin, pull requests merged in 2019-12, with the labels that each got.

#480 3401 return after pub
  .gitignore
  joplin/urls.py
  yarn.lock
Labels: PR: unreviewed

#479 3218 go fast
  .circleci/config.yml
  .circleci/docker/joplin-base.Dockerfile
  .circleci/docker/joplin-ci-build.Dockerfile
  .circleci/docker/joplin-ci-deploy.Dockerfile
  .circleci/docker/joplin-ci.Dockerfile
  .circleci/docker/push.sh
  .circleci/scripts/check_app_status.py
  .circleci/scripts/migrate.sh
  .circleci/scripts/print_vars.sh
  .circleci/scripts/set_pr_vars.sh
  .circleci/vars/branch_overrides.py
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README.md
  app.Dockerfile
  docker-compose.load_new_datadump_override.yml
  docker-compose.local_override.yml
  docker-compose.migration_test_override.yml
  docker-compose.yml
  docker-entrypoint.sh
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/migrations/0102_deploymentlog.py
  joplin/base/models/__init__.py
  joplin/base/models/deployment_log.py
  joplin/base/signals/aws_publish.py
  joplin/base/signals/netlify_publish.py
  joplin/db/scripts/sanitize_revision_data.sql
  joplin/settings.py
  scripts/migration-test.sh
  scripts/serve-local.sh
Labels: PR: reviewed-approved, wip

#488 Issue 3503: memory bugs
  .circleci/scripts/check_app_status.py
  Pipfile
  Pipfile.lock
  joplin/settings.py
Labels: PR: unreviewed

#489 master > prod 12/10/19 Scout APM
  .circleci/scripts/check_app_status.py
  Pipfile
  Pipfile.lock
  joplin/settings.py
Labels: PR: unreviewed

#486 3462 add location page to create content modal
  joplin/base/views/joplin_views.py
  joplin/js/CreateContentModal/ChooseTitleStep.js
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/js/CreateContentModal/index.js
  joplin/static/images/location.png
Labels: PR: reviewed-approved

#490 set WEB_CONCURRENCY as configurable env var
  .circleci/docker/joplin-base.Dockerfile
  .circleci/vars/branch_overrides.py
  .circleci/vars/heroku_pr_vars.py
  app.Dockerfile
Labels: PR: unreviewed

#487 server tweaks
  .circleci/scripts/check_app_status.py
  app.Dockerfile
  gunicorn.conf.py
  joplin/urls.py
Labels: PR: unreviewed

#493 Add load testing and performance monitorization!
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README.md
  joplin/settings.py
  joplin/urls.py
  locustfile.py
  template.env
Labels: PR: unreviewed

#495 Master --> Prod
  .circleci/docker/joplin-base.Dockerfile
  .circleci/scripts/check_app_status.py
  .circleci/vars/branch_overrides.py
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README.md
  app.Dockerfile
  gunicorn.conf.py
  joplin/base/views/joplin_views.py
  joplin/js/CreateContentModal/ChooseTitleStep.js
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/js/CreateContentModal/index.js
  joplin/settings.py
  joplin/static/images/location.png
  joplin/urls.py
  locustfile.py
  template.env
Labels: PR: unreviewed

#497 tweak so not having silk installed dosen't break builds
  Pipfile.lock
  joplin/settings.py
Labels: PR: unreviewed

#492 3535 - location pages - api changes
  joplin/api/content_type_map.py
  joplin/api/schema.py
Labels: PR: reviewed-approved

#498 2780 clean up 2
  .circleci/cleanup/README.md
  .circleci/cleanup/build_zappa_settings.py
  .circleci/cleanup/deploy.sh
  .circleci/cleanup/main.py
Labels: PR: unreviewed

#500 getting location stuff into prod
  gunicorn.conf.py
  joplin/api/content_type_map.py
  joplin/api/schema.py
  joplin/settings.py
Labels: PR: unreviewed

#503 3623 Translated nested Streamfields broken on wagtail 2.7
  joplin/js/editor.js
Labels: PR: reviewed-approved

#505 * crossing fingers emoji *
  .circleci/scripts/check_app_status.py
Labels: PR: reviewed-approved

#506 patch to prevent heroku cli warning from preventing build
  .circleci/scripts/check_app_status.py
  .circleci/vars/heroku_pr_vars.py
Labels: PR: unreviewed

#502 3537 - add documents to the rich text field
  README.md
  joplin/base/models/constants.py
Labels: PR: reviewed-approved

#501 3622 "Location name" in content type title fields
  joplin/locations/models.py
Labels: PR: unreviewed
