Repository cityofaustin/joplin, pull requests merged in 2019-10, with the labels that each got.

#404 guide page previews
  joplin/api/schema.py
Labels: wip

#421 coa-publisher into production
  .circleci/scripts/create_review_app.sh
  .circleci/scripts/print_vars.sh
  .circleci/scripts/set_pr_vars.sh
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  README/toggle_flag_state.png
  deploy/requirements.txt
  docker-entrypoint.sh
  joplin/api/schema.py
  joplin/base/apps.py
  joplin/base/migrations/0093_janisbranchsettings.py
  joplin/base/migrations/0095_merge_20191021_2137.py
  joplin/base/models/__init__.py
  joplin/base/models/constants.py
  joplin/base/models/information_page.py
  joplin/base/models/janis_page.py
  joplin/base/models/site_settings.py
  joplin/base/signals.py
  joplin/base/signals/aws_publish.py
  joplin/base/signals/image_publish.py
  joplin/base/signals/netlify_publish.py
  joplin/base/templatetags/joplin_tags.py
  joplin/base/views/joplin_views.py
  joplin/base/wagtail_hooks.py
  joplin/css/layouts/left_sidebar_nav.scss
  joplin/db/fixtures/janis_branch_settings.json
  joplin/db/fixtures/local_admin_user.json
  joplin/db/system-generated/local_admin_user.json
  joplin/db/system-generated/seeding_datadump_metadata.txt
  joplin/js/editor.js
  joplin/js/janisBranchSettings.js
  joplin/settings.py
  joplin/templates/wagtailadmin/pages/edit.html
  joplin/templates/wagtailadmin/pages/edit/sidebar-preview.html
  joplin/templates/wagtailadmin/shared/page_status_tag.html
  joplin/webpack.base.js
  scripts/remove_logs_from_json_stream.py
  scripts/serve-local.sh
  scripts/setup-undockered-data.sh
  template.env
Labels: PR: unreviewed

#426 3199-Fix duplicate slugs showing
  joplin/base/models/janis_page.py
Labels: PR: reviewed-approved

#422 3285-error-messages
  joplin/base/models/janis_page.py
  scripts/migration-test.sh
Labels: PR: reviewed-approved

#428 2963 themes
  joplin/base/context_processors.py
  joplin/css/theme-override.scss
  joplin/css/variables.scss
  joplin/js/theme.js
  joplin/templates/wagtailadmin/base.html
  joplin/templates/wagtailadmin/login.html
  joplin/webpack.base.js
Labels: PR: unreviewed

#439 2581 tweaks
  joplin/base/views/joplin_search_views.py
  joplin/settings.py
  joplin/templates/wagtailadmin/pages/coa_header.html
  joplin/templates/wagtailadmin/pages/index.html
  joplin/templates/wagtailadmin/pages/search_header.html
Labels: PR: unreviewed

#418 2581 Joplin content main page
  joplin/base/views/joplin_search_views.py
  joplin/base/views/joplin_views.py
  joplin/base/wagtail_hooks.py
  joplin/css/layouts/headers.scss
  joplin/js/CreateContentModal/index.scss
  joplin/settings.py
  joplin/templates/wagtailadmin/pages/coa_header.html
  joplin/templates/wagtailadmin/pages/index.html
  joplin/templates/wagtailadmin/pages/listing/_table_headers_explore.html
  joplin/templates/wagtailadmin/pages/search.html
  joplin/templates/wagtailadmin/pages/search_header.html
  joplin/templates/wagtailadmin/pages/search_results.html
  joplin/urls.py
Labels: PR: unreviewed

#444 Master -> Prod :: Search Page
  joplin/base/views/joplin_search_views.py
  joplin/base/views/joplin_views.py
  joplin/base/wagtail_hooks.py
  joplin/css/layouts/headers.scss
  joplin/js/CreateContentModal/index.scss
  joplin/settings.py
  joplin/templates/wagtailadmin/pages/coa_header.html
  joplin/templates/wagtailadmin/pages/index.html
  joplin/templates/wagtailadmin/pages/listing/_table_headers_explore.html
  joplin/templates/wagtailadmin/pages/search.html
  joplin/templates/wagtailadmin/pages/search_header.html
  joplin/templates/wagtailadmin/pages/search_results.html
  joplin/urls.py
Labels: PR: unreviewed
