Repository cityofaustin/joplin, pull requests merged in 2020-05, with the labels that each got.

#687 Import everything
  .circleci/vars/branch_overrides.py
  .circleci/vars/heroku_pr_vars.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/importer/create_from_importer.py
  joplin/importer/import_everything.py
  joplin/importer/queries.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
Labels: PR: unreviewed

#720 v 3.0.1 master => production
  .circleci/config.yml
Labels: PR: unreviewed

#716 4215 adding related events to pages
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/pages/event_page/migrations/0002_eventpagerelatedpage.py
  joplin/pages/event_page/migrations/0003_auto_20200427_1835.py
  joplin/pages/event_page/models.py
Labels: PR: partially-approved

#725 3.1.0 adding related events to information, service and location pages
  .circleci/config.yml
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/pages/event_page/migrations/0002_eventpagerelatedpage.py
  joplin/pages/event_page/migrations/0003_auto_20200427_1835.py
  joplin/pages/event_page/models.py
Labels: PR: unreviewed

#724 4355 News
  joplin/api/schema.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/translation.py
  joplin/base/views/new_page_from_modal.py
  joplin/groups/fixtures/test_cases/mvp_news_aph.py
  joplin/groups/fixtures/test_cases/mvp_news_cpio.py
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/department_page/fixtures/helpers/components.py
  joplin/pages/news_page/__init__.py
  joplin/pages/news_page/admin.py
  joplin/pages/news_page/apps.py
  joplin/pages/news_page/factories.py
  joplin/pages/news_page/fixtures/__init__.py
  joplin/pages/news_page/fixtures/helpers/components.py
  joplin/pages/news_page/fixtures/helpers/create_fixture.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH_written_for_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_CPIO_written_for_APH.py
  joplin/pages/news_page/management/commands/load_test_news_pages.py
  joplin/pages/news_page/migrations/0001_initial.py
  joplin/pages/news_page/migrations/0002_auto_20200508_1207.py
  joplin/pages/news_page/migrations/__init__.py
  joplin/pages/news_page/models.py
  joplin/pages/news_page/tests.py
  joplin/pages/news_page/views.py
  joplin/pages/news_page/wagtail_hooks.py
  joplin/settings.py
  joplin/snippets/contact/factories.py
  joplin/snippets/contact/fixtures/helpers/components.py
Labels: PR: unreviewed

#727 master -> prod v3.2.0
  .circleci/config.yml
  joplin/api/schema.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/translation.py
  joplin/base/views/new_page_from_modal.py
  joplin/groups/fixtures/test_cases/mvp_news_aph.py
  joplin/groups/fixtures/test_cases/mvp_news_cpio.py
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/department_page/fixtures/helpers/components.py
  joplin/pages/news_page/__init__.py
  joplin/pages/news_page/admin.py
  joplin/pages/news_page/apps.py
  joplin/pages/news_page/factories.py
  joplin/pages/news_page/fixtures/__init__.py
  joplin/pages/news_page/fixtures/helpers/components.py
  joplin/pages/news_page/fixtures/helpers/create_fixture.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH_written_for_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_CPIO_written_for_APH.py
  joplin/pages/news_page/management/commands/load_test_news_pages.py
  joplin/pages/news_page/migrations/0001_initial.py
  joplin/pages/news_page/migrations/0002_auto_20200508_1207.py
  joplin/pages/news_page/migrations/__init__.py
  joplin/pages/news_page/models.py
  joplin/pages/news_page/tests.py
  joplin/pages/news_page/views.py
  joplin/pages/news_page/wagtail_hooks.py
  joplin/settings.py
  joplin/snippets/contact/factories.py
  joplin/snippets/contact/fixtures/helpers/components.py
Labels: PR: unreviewed

#728 Issue 4371: fix bugs with editing your own user
  joplin/users/forms.py
Labels: PR: reviewed-approved

#730 master => prod v3.2.0
  joplin/users/forms.py
Labels: PR: unreviewed

#729 4380 publish bug
  joplin/pages/base_page/models.py
  joplin/pages/topic_page/models.py
  joplin/publish_preflight/requirements.py
Labels: PR: unreviewed

#731 prod to 3.2.2
  joplin/pages/base_page/models.py
  joplin/pages/topic_page/models.py
  joplin/publish_preflight/requirements.py
Labels: PR: unreviewed

#732 4098 Users creating pages in joplin have departments
  joplin/pages/base_page/models.py
  joplin/pages/information_page/models.py
  joplin/users/fixtures/__init__.py
  joplin/users/fixtures/administrative/editor_for_test_env.py
  joplin/users/fixtures/helpers/create_fixture.py
  joplin/users/tests/conftest.py
  joplin/users/tests/tests.py
Labels: PR: partially-approved
