Repository cityofaustin/joplin, pull requests merged in 2020-04, with the labels that each got.

#640 Issue 4239: move SiteSettings to the HomePage
  .circleci/vars/branch_overrides.py
  .gitignore
  joplin/api/schema.py
  joplin/base/migrations/0003_delete_janisbranchsettings.py
  joplin/base/models/__init__.py
  joplin/base/models/site_settings.py
  joplin/base/signals/janis_build_triggers.py
  joplin/base/signals/netlify_publish.py
  joplin/base/signals/publish_v3.py
  joplin/base/templatetags/joplin_tags.py
  joplin/base/views/content_list_view_publish.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/wagtail_hooks.py
  joplin/conftest.py
  joplin/js/janisBranchSettings.js
  joplin/pages/base_page/factories.py
  joplin/pages/base_page/models.py
  joplin/pages/base_page/tests.py
  joplin/pages/department_page/models.py
  joplin/pages/department_page/tests.py
  joplin/pages/home_page/fixtures/__init__.py
  joplin/pages/home_page/fixtures/helpers/create_fixture.py
  joplin/pages/home_page/fixtures/test_cases/pytest.py
  joplin/pages/home_page/migrations/0003_auto_20200403_1537.py
  joplin/pages/home_page/migrations/0004_auto_20200404_2009.py
  joplin/pages/home_page/models.py
  joplin/pages/location_page/models.py
  joplin/pages/location_page/tests.py
  joplin/pages/topic_collection_page/models.py
  joplin/pages/topic_collection_page/tests.py
  joplin/pages/topic_page/models.py
  joplin/templates/wagtailadmin/shared/page_status_tag.html
  joplin/webpack.base.js
Labels: PR: unreviewed

#638 4223 - topic collections resolve their topics and top pages
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
Labels: PR: reviewed-approved

#637 4219 import location page related service hours
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/pages/location_page/factories.py
  joplin/pages/location_page/tests.py
Labels: PR: partially-approved

#643 4256 resolver for users on v2
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README/authorization_graphql.md
  README/get_graphql_auth_token.png
  joplin/api/schema.py
  joplin/settings.py
Labels: PR: partially-approved

#648 Revert "4256 resolver for users on v2 "
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README/authorization_graphql.md
  README/get_graphql_auth_token.png
  joplin/api/schema.py
  joplin/settings.py
Labels: PR: unreviewed

#649 Localized docs to pytest
  joplin/api/schema.py
  joplin/api/snapshots/snap_test_api.py
  joplin/base/migrations/0008_auto_20200313_1917.py
  joplin/base/migrations/0009_officialdocumentpageofficialdocument_document_es.py
  joplin/base/migrations/0010_auto_20200321_0246.py
  joplin/base/models/official_documents_page.py
  joplin/base/translation.py
  joplin/settings.py
Labels: PR: unreviewed

#644 4184 event page janis urls
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/event_page/factories.py
  joplin/pages/event_page/fixtures/__init__.py
  joplin/pages/event_page/fixtures/helpers/components.py
  joplin/pages/event_page/fixtures/helpers/create_fixture.py
  joplin/pages/event_page/fixtures/test_cases/title.py
  joplin/pages/event_page/management/commands/load_test_event_pages.py
  joplin/pages/event_page/models.py
  joplin/pages/event_page/tests.py
  joplin/pages/location_page/models.py
Labels: PR: partially-approved

#650 4170 documents
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/translation.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/pages/event_page/factories.py
  joplin/pages/official_documents_page/factories.py
  joplin/pages/official_documents_page/migrations/0002_auto_20200407_1046.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/official_documents_page/tests.py
  joplin/settings.py
Labels: PR: partially-approved

#647 update circleci docker images
  .circleci/config.yml
  .circleci/docker/push.sh
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README/authorization_graphql.md
  README/get_graphql_auth_token.png
  app.Dockerfile
  joplin/api/schema.py
  joplin/settings.py
Labels: PR: unreviewed, demo, wip

#651 maybe fix unknown blob circleci issue
  .circleci/scripts/helpers.sh
Labels: PR: unreviewed

#652 only push joplin images to heroku, not dockerhub
  .circleci/scripts/build_image.sh
  .circleci/scripts/helpers.sh
Labels: PR: unreviewed

#653 v2.8.2 master => prod
  .circleci/config.yml
  .circleci/docker/push.sh
  .circleci/scripts/build_image.sh
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README/authorization_graphql.md
  README/get_graphql_auth_token.png
  app.Dockerfile
  joplin/api/schema.py
  joplin/settings.py
Labels: PR: unreviewed

#646 merge master into v3 for user resolvers
  .circleci/config.yml
  .circleci/docker/push.sh
  .circleci/scripts/build_image.sh
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README/authorization_graphql.md
  README/get_graphql_auth_token.png
  app.Dockerfile
  joplin/api/schema.py
  joplin/api/snapshots/snap_test_api.py
  joplin/base/translation.py
  joplin/pages/official_documents_page/models.py
  joplin/settings.py
Labels: PR: unreviewed

#655 v2.8.3 master => prod hotfix
  joplin/api/schema.py
Labels: PR: unreviewed

#656 V3 users hotfix
  joplin/api/schema.py
Labels: PR: unreviewed

#657 4169 import department pages
  .circleci/vars/branch_overrides.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/pages/department_page/factories.py
  joplin/pages/department_page/tests.py
Labels: PR: partially-approved

#659 4257 user importer
  joplin/importer/create_from_importer.py
  joplin/importer/page_importer.py
  joplin/importer/tests.py
  joplin/pages/base_page/factories.py
  joplin/pages/department_page/factories.py
  joplin/pages/event_page/factories.py
  joplin/pages/information_page/factories.py
  joplin/pages/information_page/tests.py
  joplin/pages/location_page/factories.py
  joplin/pages/official_documents_page/factories.py
  joplin/pages/service_page/factories.py
  joplin/pages/topic_collection_page/factories.py
  joplin/pages/topic_collection_page/tests.py
  joplin/pages/topic_page/factories.py
  joplin/pages/topic_page/tests.py
Labels: PR: reviewed-approved, wip

#661 Official docs fixture
  .circleci/vars/branch_overrides.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/official_documents_page/fixtures/__init__.py
  joplin/pages/official_documents_page/fixtures/helpers/components.py
  joplin/pages/official_documents_page/fixtures/helpers/create_fixture.py
  joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/official_documents_page/management/commands/load_test_official_documents_pages.py
  joplin/pages/official_documents_page/tests.py
Labels: PR: partially-approved

#663 Event page url error
  joplin/pages/event_page/models.py
  joplin/pages/event_page/tests.py
  joplin/snippets/theme/fixtures/test_cases/kitchen_sink.py
Labels: PR: reviewed-approved

#662 this was causing issues
  joplin/snippets/theme/fixtures/test_cases/kitchen_sink.py
Labels: PR: reviewed-approved

#665 spell document correctly
  joplin/api/schema.py
Labels: PR: partially-approved

#666 Fixtures and previews
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
Labels: PR: reviewed-approved

#611 don't merge - 4116 importer j2 test data
  .circleci/config.yml
  joplin/db/system-generated/dummy.datadump.json
  joplin/db/system-generated/dummy_datadump_metadata.txt
  joplin/db/system-generated/prod.datadump.json
  joplin/db/system-generated/prod_datadump_metadata.txt
Labels: PR: unreviewed, wip

#673 fix publishing on guide pages
  .circleci/vars/branch_overrides.py
  joplin/pages/guide_page/models.py
Labels: PR: partially-approved

#674 4257: import form_container
  README/add_new_content_type.md
  joplin/importer/queries.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/form_container/factories.py
  joplin/pages/form_container/tests.py
Labels: PR: partially-approved

#672 4257 user importer
  .circleci/vars/heroku_pr_vars.py
  README.md
  README/add_new_content_type.md
  README/authorization_graphql.md
  README/environment_variables.md
  README/images/authoring_interface.png
  README/images/get_graphql_auth_token.png
  README/images/janis.png
  README/images/myapp_models.png
  README/images/server_success.png
  README/images/toggle_flag_state.png
  joplin/base/apps.py
  joplin/base/context_processors.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/signals/janis_build_triggers.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/wagtail_hooks.py
  joplin/conftest.py
  joplin/db/fixtures/janis_branch_settings.json
  joplin/db/fixtures/local_admin_user.json
  joplin/importer/create_from_importer.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/js/CreateContentModal/ChooseTitleStep.js
  joplin/js/CreateContentModal/index.js
  joplin/js/admin.js
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/base_page/models.py
  joplin/pages/department_page/tests.py
  joplin/pages/event_page/fixtures/helpers/create_fixture.py
  joplin/pages/form_container/factories.py
  joplin/pages/form_container/tests.py
  joplin/pages/home_page/models.py
  joplin/pages/information_page/fixtures/helpers/create_fixture.py
  joplin/pages/information_page/tests.py
  joplin/pages/location_page/fixtures/helpers/create_fixture.py
  joplin/pages/location_page/tests.py
  joplin/pages/official_documents_page/fixtures/helpers/create_fixture.py
  joplin/pages/official_documents_page/tests.py
  joplin/pages/service_page/fixtures/helpers/create_fixture.py
  joplin/pages/service_page/tests.py
  joplin/pages/topic_collection_page/fixtures/helpers/create_fixture.py
  joplin/pages/topic_collection_page/models.py
  joplin/pages/topic_page/fixtures/helpers/create_fixture.py
  joplin/settings.py
  joplin/snippets/contact/tests.py
  joplin/snippets/theme/fixtures/helpers/create_fixture.py
  joplin/templates/joplin_UI/application_banner.html
  joplin/templates/wagtailadmin/base.html
  joplin/templates/wagtailadmin/login.html
  joplin/users/factories.py
  joplin/users/fixtures/__init__.py
  joplin/users/fixtures/administrative/admin_for_test_env.py
  joplin/users/fixtures/administrative/superadmin.py
  joplin/users/fixtures/helpers/create_fixture.py
  joplin/users/management/commands/load_admin_for_test_env.py
  template.env
Labels: PR: unreviewed

#676 Steps with options
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/service_page/fixtures/test_cases/step_with_options.py
  joplin/pages/service_page/tests.py
Labels: PR: partially-approved

#678 4274 are we live? (import live/draft with importer)
  .circleci/vars/branch_overrides.py
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/pages/information_page/tests.py
Labels: PR: partially-approved

#667 Not top pages topics
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
Labels: PR: reviewed-approved

#681 4273 correct ids
  .circleci/vars/branch_overrides.py
  joplin/api/content_type_map.py
  joplin/api/schema.py
Labels: PR: partially-approved

#684 Api page type and description
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
Labels: PR: unreviewed

#689 4280 skip step with location
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/service_page/fixtures/test_cases/steps_with_location.py
  joplin/pages/service_page/tests.py
Labels: PR: reviewed-approved

#690 Issue 4264: import event page
  .gitignore
  README/testing.md
  joplin/importer/create_from_importer.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/pages/base_page/fixtures/helpers/streamfieldify.py
  joplin/pages/base_page/tests.py
  joplin/pages/event_page/factories.py
  joplin/pages/event_page/fixtures/__init__.py
  joplin/pages/event_page/fixtures/helpers/components.py
  joplin/pages/event_page/fixtures/test_cases/at_city_location.py
  joplin/pages/event_page/fixtures/test_cases/at_remote_location.py
  joplin/pages/event_page/fixtures/test_cases/three_fees.py
  joplin/pages/event_page/tests.py
  joplin/pages/official_documents_page/factories.py
  joplin/pages/service_page/fixtures/helpers/components.py
Labels: PR: unreviewed

#693 4275 step with location
  joplin/importer/create_from_importer.py
  joplin/pages/home_page/models.py
  joplin/pages/location_page/fixtures/__init__.py
  joplin/pages/location_page/fixtures/test_cases/live_city_hall.py
  joplin/pages/location_page/fixtures/test_cases/live_library.py
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/service_page/fixtures/test_cases/step_with_1_location.py
  joplin/pages/service_page/fixtures/test_cases/step_with_2_locations.py
  joplin/pages/service_page/tests.py
Labels: PR: unreviewed

#695 4282 homepage
  .circleci/vars/branch_overrides.py
  joplin/pages/home_page/models.py
Labels: PR: reviewed-approved, wip

#682 Add live and latest to page revision query
  joplin/api/schema.py
Labels: PR: partially-approved

#694 4288 internal links
  .circleci/vars/branch_overrides.py
  joplin/importer/page_importer.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/placeholder_for_internal_links.py
  joplin/pages/service_page/fixtures/test_cases/step_with_internal_links.py
  joplin/pages/service_page/tests.py
  joplin/pages/topic_page/fixtures/__init__.py
  joplin/pages/topic_page/fixtures/test_cases/title.py
Labels: PR: partially-approved

#696 Latest revision master to v3
  joplin/api/schema.py
Labels: PR: partially-approved

#698 4281 don't import english into spanish fields
  .circleci/vars/branch_overrides.py
  joplin/importer/create_from_importer.py
  joplin/pages/service_page/tests.py
Labels: PR: partially-approved

#697 Issue 4298: fix the homepage
  docker-entrypoint.sh
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/management/commands/load_mandatory_fixtures.py
  joplin/conftest.py
  joplin/pages/home_page/fixtures/__init__.py
  joplin/pages/home_page/fixtures/administrative/root_home_page.py
  joplin/pages/home_page/migrations/0002_auto_20200410_1151.py
  joplin/pages/home_page/migrations/0002_remove_default_homepage.py
  joplin/pages/home_page/models.py
Labels: PR: unreviewed

#699 allow local full site builds; redirect to https
  joplin/settings.py
Labels: PR: partially-approved

#700 Spanish steps with locations
  .circleci/vars/branch_overrides.py
  joplin/importer/create_from_importer.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/step_with_location_first_then_basic_step.py
  joplin/pages/service_page/tests.py
Labels: PR: partially-approved

#701 Remove map blocks from api
  joplin/api/schema.py
Labels: PR: unreviewed, wip

#702 master -> prod 2.9.0
  joplin/api/schema.py
Labels: PR: unreviewed

#703 Resolve Janis Preview Instances
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
Labels: PR: partially-approved

#706 4317 until we support importing images don't try to import them
  joplin/importer/create_from_importer.py
Labels: PR: partially-approved

#708 Issue 4092: use publish_v3 for staging and production
  joplin/base/signals/janis_build_triggers.py
  joplin/base/signals/publish_v3.py
Labels: PR: unreviewed

#709 just always rebuild for now
  joplin/base/signals/publish_v3.py
Labels: PR: reviewed-approved

#710 4340 official documents resolver
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
Labels: PR: reviewed-approved, wip

#713 just hardcode to slug_en for now
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/event_page/models.py
  joplin/pages/location_page/models.py
  joplin/pages/topic_collection_page/models.py
  joplin/pages/topic_page/models.py
Labels: PR: partially-approved

#714 missed a spot
  joplin/pages/topic_collection_page/models.py
Labels: PR: unreviewed

#715 just add it to the query
  joplin/importer/queries.py
Labels: PR: reviewed-approved

#717 set correct publish_janis_branch for staging and prod
  joplin/pages/home_page/models.py
Labels: PR: partially-approved
