Repository cityofaustin/joplin, pull requests merged in 2020-03, with the labels that each got.

#578 3987 test with factories
  .circleci/config.yml
  .circleci/docker/joplin-base.Dockerfile
  .gitignore
  Pipfile
  Pipfile.lock
  README/testing.md
  app.Dockerfile
  joplin/api/snapshots/__init__.py
  joplin/api/snapshots/snap_test_api.py
  joplin/api/test_api.py
  joplin/base/factories/__init__.py
  joplin/base/factories/department_page.py
  joplin/base/factories/guide_page.py
  joplin/base/factories/information_page.py
  joplin/base/factories/offical_documents_page.py
  joplin/base/factories/service_page.py
  joplin/base/factories/topic_collection_page.py
  joplin/base/factories/topic_page.py
  joplin/base/models/department_page.py
  joplin/base/models/guide_page.py
  joplin/base/models/information_page.py
  joplin/base/tests/test_incremental_builds.py
  joplin/base/tests/test_information_page.py
  joplin/base/views/content_list_view_publish.py
  joplin/conftest.py
  joplin/locations/factories.py
  joplin/publish_preflight/tests/test_information_page_publish_preflight.py
  joplin/publish_preflight/tests/utils/load_test_data.py
  pytest.ini
  setup.cfg
Labels: PR: reviewed-approved

#600 fix tests
  joplin/api/snapshots/snap_test_api.py
  joplin/base/factories/information_page.py
Labels: PR: reviewed-approved

#601 2.7.3 -- update tests
  joplin/api/snapshots/snap_test_api.py
  joplin/base/factories/information_page.py
Labels: PR: unreviewed

#586 4016 Joplin UI: Application Banner & Primary Navigation
  README/Joplin_UI_Dev_Notes.md
  joplin/css/admin.scss
  joplin/joplin_UI/_joplin_ui_transition.scss
  joplin/joplin_UI/admin.scss
  joplin/joplin_UI/application_banner.scss
  joplin/joplin_UI/pages/pages.scss
  joplin/joplin_UI/primary_navigation.scss
  joplin/joplin_UI/variables.scss
  joplin/js/admin.js
  joplin/static/images/coa_seal_transparent_color.png
  joplin/static/images/icon_down_arrow.svg
  joplin/templates/joplin_UI/application_banner.html
  joplin/templates/joplin_UI/index.html
  joplin/templates/joplin_UI/primary_navigation.html
  joplin/templates/wagtailadmin/base.html
  joplin/templates/wagtailadmin/pages/search.html
  joplin/templates/wagtailadmin/skeleton.html
Labels: PR: reviewed-approved

#602 fixing svg directory issue
  joplin/joplin_UI/application_banner.scss
  joplin/templates/joplin_UI/application_banner.html
Labels: PR: reviewed-approved

#603 v2.7.3 master => prod
  README/Joplin_UI_Dev_Notes.md
  joplin/css/admin.scss
  joplin/joplin_UI/_joplin_ui_transition.scss
  joplin/joplin_UI/admin.scss
  joplin/joplin_UI/application_banner.scss
  joplin/joplin_UI/pages/pages.scss
  joplin/joplin_UI/primary_navigation.scss
  joplin/joplin_UI/variables.scss
  joplin/js/admin.js
  joplin/static/images/coa_seal_transparent_color.png
  joplin/static/images/icon_down_arrow.svg
  joplin/templates/joplin_UI/application_banner.html
  joplin/templates/joplin_UI/index.html
  joplin/templates/joplin_UI/primary_navigation.html
  joplin/templates/wagtailadmin/base.html
  joplin/templates/wagtailadmin/pages/search.html
  joplin/templates/wagtailadmin/skeleton.html
Labels: PR: unreviewed

#604 4042 - unpublished pages still appearing/
  README.md
  joplin/api/schema.py
  joplin/settings.py
Labels: PR: unreviewed

#607 content type filtering for search
  joplin/base/views/joplin_search_views.py
Labels: PR: unreviewed

#610 3690 incremental
  .circleci/vars/branch_overrides.py
  .circleci/vars/heroku_pr_vars.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/signals/janis_build_triggers.py
  joplin/base/signals/publish_v2.py
  joplin/pages/base_page/models.py
  joplin/settings.py
  setup.cfg
  template.env
Labels: PR: reviewed-approved

#609 4116 importer
  Pipfile
  Pipfile.lock
  joplin/base/views/new_page_from_modal.py
  joplin/importer/apps.py
  joplin/importer/checks.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/js/CreateContentModal/ChooseTitleStep.js
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/js/CreateContentModal/index.js
  joplin/pages/base_page/factories.py
  joplin/pages/base_page/migrations/0002_janisbasepage_imported_revision_id.py
  joplin/pages/base_page/models.py
  joplin/pages/base_page/tests.py
  joplin/pages/information_page/factories.py
  joplin/pages/information_page/test_information_page.py
  joplin/pages/information_page/tests.py
  joplin/pages/official_documents_page/factories.py
  joplin/pages/topic_collection_page/factories.py
  joplin/pages/topic_collection_page/tests.py
  joplin/pages/topic_page/factories.py
  joplin/pages/topic_page/tests.py
  joplin/settings.py
Labels: PR: unreviewed

#616 Issue 4148: use custom home_page content type
  .circleci/vars/branch_overrides.py
  joplin/base/views/joplin_search_views.py
  joplin/base/views/new_page_from_modal.py
  joplin/pages/home_page/migrations/0002_create_homepage.py
  joplin/pages/information_page/factories.py
  joplin/pages/topic_collection_page/factories.py
  joplin/pages/topic_page/factories.py
Labels: PR: unreviewed

#618 Issue 4142: fix spontaneous pytest breakings
  .circleci/config.yml
  .circleci/vars/branch_overrides.py
  joplin/groups/factories.py
  joplin/pages/base_page/tests.py
Labels: PR: unreviewed

#621 4076 v3 local docs
  joplin/api/schema.py
  joplin/pages/official_documents_page/migrations/0002_auto_20200324_1804.py
  joplin/pages/official_documents_page/models.py
  joplin/settings.py
Labels: PR: reviewed-approved

#622 4165: support streamfields in service_page imports
  .circleci/vars/branch_overrides.py
  joplin/conftest.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/pages/base_page/factories.py
  joplin/pages/base_page/migrations/0003_auto_20200324_2134.py
  joplin/pages/base_page/models.py
  joplin/pages/base_page/tests.py
  joplin/pages/department_page/factories.py
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/fixtures/with_steps.py
  joplin/pages/service_page/management/commands/load_test_service_pages.py
  joplin/pages/service_page/tests.py
  joplin/pages/topic_page/factories.py
Labels: PR: reviewed-approved

#617 v3 api - add nodes for pages with topics and pages with topic collections
  joplin/api/schema.py
Labels: PR: reviewed-approved

#624 4181 import langs
  Pipfile
  Pipfile.lock
  joplin/base/views/new_page_from_modal.py
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/pages/information_page/factories.py
  joplin/pages/information_page/tests.py
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/tests.py
  joplin/pages/topic_collection_page/factories.py
  joplin/pages/topic_collection_page/tests.py
  joplin/pages/topic_page/factories.py
  joplin/pages/topic_page/tests.py
Labels: PR: reviewed-approved

#625 4165 - tests with fixtures
  .circleci/vars/branch_overrides.py
  .idea/runConfigurations/Run_tests.xml
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/helpers/create_fixture.py
  joplin/pages/service_page/fixtures/test_cases/steps_2.py
  joplin/pages/service_page/fixtures/test_cases/steps_with_appblocks.py
  joplin/pages/service_page/fixtures/test_cases/title.py
  joplin/pages/service_page/fixtures/with_steps.py
  joplin/pages/service_page/management/commands/load_test_service_pages.py
  joplin/pages/service_page/tests.py
Labels: PR: unreviewed

#626 clean up importer queries
  joplin/importer/queries.py
Labels: PR: reviewed-approved

#628 load dummy data on v3 pr app
  .circleci/vars/branch_overrides.py
Labels: PR: unreviewed

#630 cleanup for the cleanup
  joplin/pages/home_page/migrations/0002_auto_20200326_2331.py
  joplin/pages/service_page/migrations/0002_auto_20200326_2344.py
  joplin/pages/service_page/models.py
Labels: PR: unreviewed

#631 Service page with contact fixture
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/wagtail_hooks.py
  joplin/pages/service_page/fixtures/__init__.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/new_contact.py
  joplin/pages/service_page/tests.py
Labels: PR: unreviewed

#632 4219 import location page
  joplin/importer/page_importer.py
  joplin/importer/queries.py
  joplin/importer/tests.py
  joplin/pages/location_page/factories.py
  joplin/pages/location_page/fixtures/__init__.py
  joplin/pages/location_page/fixtures/helpers/components.py
  joplin/pages/location_page/fixtures/helpers/create_fixture.py
  joplin/pages/location_page/fixtures/test_cases/title.py
  joplin/pages/location_page/management/commands/load_test_location_pages.py
  joplin/pages/location_page/tests.py
  joplin/pages/location_page_old/factories.py
  joplin/pages/location_page_old/fixture_data.json
  joplin/pages/location_page_old/fixtures.py
  joplin/pages/location_page_old/tests.py.old
Labels: PR: reviewed-approved

#634 resolve departments and topic collections
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/pages/topic_page/models.py
Labels: PR: partially-approved

#635 Issue 4047: separate roles and departments when creating new user
  .circleci/vars/branch_overrides.py
  README.md
  README/testing.md
  joplin/css/pages/edit.scss
  joplin/groups/factories.py
  joplin/groups/fixtures/__init__.py
  joplin/groups/fixtures/helpers/create_fixture.py
  joplin/groups/fixtures/test_cases/title.py
  joplin/pages/base_page/factories.py
  joplin/pages/base_page/tests.py
  joplin/pages/department_page/tests.py
  joplin/pages/information_page/factories.py
  joplin/pages/service_page/factories.py
  joplin/pages/topic_collection_page/factories.py
  joplin/pages/topic_page/factories.py
  joplin/publish_preflight/tests/utils/make_form.py
  joplin/settings.py
  joplin/templates/wagtailusers/users/create.html
  joplin/templates/wagtailusers/users/edit.html
  joplin/users/forms.py
  joplin/users/js/index.js
  joplin/users/templatetags/user_tags.py
  joplin/users/tests/__init__.py
  joplin/users/tests/conftest.py
  joplin/users/tests/tests.py
  joplin/users/tests/utils/make_user_form.py
  joplin/users/views/users.py
  joplin/webpack.base.js
Labels: PR: unreviewed

#636 4146 loc urls
  .circleci/vars/branch_overrides.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/location_page/fixtures/test_cases/title.py
  joplin/pages/location_page/models.py
  joplin/pages/location_page/tests.py
Labels: PR: partially-approved
