Repository cityofaustin/joplin, pull requests merged in 2020-07, with the labels that each got.

#764 4503 spanish slug
  joplin/api/schema.py
  joplin/conftest.py
  joplin/pages/base_page/tests/__init__.py
  joplin/pages/event_page/tests.py
  joplin/pages/topic_collection_page/tests/__init__.py
  joplin/pages/topic_collection_page/tests/test_graphql.py
  joplin/pages/topic_collection_page/tests/tests.py
  joplin/pages/topic_page/factories.py
Labels: PR: reviewed-approved

#766 v3.2.14 master => production
  joplin/api/schema.py
  joplin/conftest.py
  joplin/pages/base_page/tests/__init__.py
  joplin/pages/event_page/tests.py
  joplin/pages/topic_collection_page/tests/__init__.py
  joplin/pages/topic_collection_page/tests/test_graphql.py
  joplin/pages/topic_collection_page/tests/tests.py
  joplin/pages/topic_page/factories.py
Labels: PR: unreviewed

#769 4600 styleguide
  joplin/base/templatetags/joplin_tags.py
Labels: PR: unreviewed

#770 v3.2.14 master => production
  joplin/base/templatetags/joplin_tags.py
Labels: PR: unreviewed

#772 allow orderBy: "-page__date" on officialDocumentCollectionDocuments
  joplin/api/schema.py
Labels: PR: unreviewed

#771 4504 mvp docs split out into collections and documents
  joplin/api/content_type_map.py
  joplin/api/schema.py
  joplin/base/forms.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/tests/test_incremental_builds.py
  joplin/base/translation.py
  joplin/base/views/new_page_from_modal.py
  joplin/js/CreateContentModal/ChooseTitleStep.js
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/pages/base_page/factories.py
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/base_page/migrations/0002_add_pageviewpermissions.py
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/official_documents_collection/__init__.py
  joplin/pages/official_documents_collection/admin.py
  joplin/pages/official_documents_collection/apps.py
  joplin/pages/official_documents_collection/factories.py
  joplin/pages/official_documents_collection/fixtures/__init__.py
  joplin/pages/official_documents_collection/fixtures/helpers/components.py
  joplin/pages/official_documents_collection/fixtures/helpers/create_fixture.py
  joplin/pages/official_documents_collection/fixtures/test_cases/kitchen_sink.py
  joplin/pages/official_documents_collection/management/commands/load_test_official_documents_collection.py
  joplin/pages/official_documents_collection/management/commands/migrate_document_model.py
  joplin/pages/official_documents_collection/management/commands/update_document_collection_slugs.py
  joplin/pages/official_documents_collection/migrations/0001_initial.py
  joplin/pages/official_documents_collection/migrations/__init__.py
  joplin/pages/official_documents_collection/models.py
  joplin/pages/official_documents_collection/tests.py
  joplin/pages/official_documents_collection/views.py
  joplin/pages/official_documents_collection/wagtail_hooks.py
  joplin/pages/official_documents_page/apps.py
  joplin/pages/official_documents_page/factories.py
  joplin/pages/official_documents_page/fixtures/__init__.py
  joplin/pages/official_documents_page/fixtures/helpers/create_fixture.py
  joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/official_documents_page/management/commands/copy_new_official_document_pages.py
  joplin/pages/official_documents_page/management/commands/remove_obsolete_doc_data.py
  joplin/pages/official_documents_page/migrations/0002_auto_20200707_0214.py
  joplin/pages/official_documents_page/migrations/0003_officialdocumentpage.py
  joplin/pages/official_documents_page/migrations/0004_officialdocumentcollectiondocument.py
  joplin/pages/official_documents_page/migrations/0005_auto_20200709_1742.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/official_documents_page/tests.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_page/factories.py
  joplin/pages/topic_page/models.py
  joplin/settings.py
Labels: PR: unreviewed

#774 make publish_succeeded endpoint async
  joplin/base/views/publish_succeeded.py
Labels: PR: reviewed-approved

#775 Joplin to 3.3.0
  joplin/api/content_type_map.py
  joplin/api/schema.py
  joplin/base/forms.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/tests/test_incremental_builds.py
  joplin/base/translation.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/views/publish_succeeded.py
  joplin/js/CreateContentModal/ChooseTitleStep.js
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/pages/base_page/factories.py
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/base_page/migrations/0002_add_pageviewpermissions.py
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/official_documents_collection/__init__.py
  joplin/pages/official_documents_collection/admin.py
  joplin/pages/official_documents_collection/apps.py
  joplin/pages/official_documents_collection/factories.py
  joplin/pages/official_documents_collection/fixtures/__init__.py
  joplin/pages/official_documents_collection/fixtures/helpers/components.py
  joplin/pages/official_documents_collection/fixtures/helpers/create_fixture.py
  joplin/pages/official_documents_collection/fixtures/test_cases/kitchen_sink.py
  joplin/pages/official_documents_collection/management/commands/load_test_official_documents_collection.py
  joplin/pages/official_documents_collection/management/commands/migrate_document_model.py
  joplin/pages/official_documents_collection/management/commands/update_document_collection_slugs.py
  joplin/pages/official_documents_collection/migrations/0001_initial.py
  joplin/pages/official_documents_collection/migrations/__init__.py
  joplin/pages/official_documents_collection/models.py
  joplin/pages/official_documents_collection/tests.py
  joplin/pages/official_documents_collection/views.py
  joplin/pages/official_documents_collection/wagtail_hooks.py
  joplin/pages/official_documents_page/apps.py
  joplin/pages/official_documents_page/factories.py
  joplin/pages/official_documents_page/fixtures/__init__.py
  joplin/pages/official_documents_page/fixtures/helpers/create_fixture.py
  joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/official_documents_page/management/commands/copy_new_official_document_pages.py
  joplin/pages/official_documents_page/management/commands/remove_obsolete_doc_data.py
  joplin/pages/official_documents_page/migrations/0002_auto_20200707_0214.py
  joplin/pages/official_documents_page/migrations/0003_officialdocumentpage.py
  joplin/pages/official_documents_page/migrations/0004_officialdocumentcollectiondocument.py
  joplin/pages/official_documents_page/migrations/0005_auto_20200709_1742.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/official_documents_page/tests.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_page/factories.py
  joplin/pages/topic_page/models.py
  joplin/settings.py
Labels: PR: unreviewed

#776 4621 preview
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/base/management/commands/make_translation_report.py
  joplin/settings.py
  scripts/sync_data.sh
Labels: PR: reviewed-approved

#779 v3.4.0 master => production
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/base/management/commands/make_translation_report.py
  joplin/settings.py
  scripts/sync_data.sh
Labels: PR: unreviewed

#773 Remove OfficalDocumentPageOld and OfficialDocumentPageDocument
  joplin/base/translation.py
  joplin/pages/location_page_old/factories.py
  joplin/pages/location_page_old/fixture_data.json
  joplin/pages/location_page_old/fixtures.py
  joplin/pages/location_page_old/tests.py.old
  joplin/pages/official_documents_page/migrations/0006_auto_20200713_1501.py
  joplin/pages/official_documents_page/models.py
Labels: PR: partially-approved

#783 joplin to v 3.4.1
  joplin/base/translation.py
  joplin/pages/location_page_old/factories.py
  joplin/pages/location_page_old/fixture_data.json
  joplin/pages/location_page_old/fixtures.py
  joplin/pages/location_page_old/tests.py.old
  joplin/pages/official_documents_page/migrations/0006_auto_20200713_1501.py
  joplin/pages/official_documents_page/models.py
Labels: PR: unreviewed

#780 Remove SEO tab and move slug field to page
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/event_page/models.py
  joplin/pages/form_container/models.py
  joplin/pages/guide_page/models.py
  joplin/pages/information_page/models.py
  joplin/pages/location_page/models.py
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_collection/models.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_collection_page/models.py
  joplin/pages/topic_page/models.py
Labels: PR: reviewed-approved

#784 joplin to 3.4.2
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/event_page/models.py
  joplin/pages/form_container/models.py
  joplin/pages/guide_page/models.py
  joplin/pages/information_page/models.py
  joplin/pages/location_page/models.py
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_collection/models.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_collection_page/models.py
  joplin/pages/topic_page/models.py
Labels: PR: unreviewed

#782 Issue 4402: add notification emails
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README.md
  joplin/base/signals/aws_publish.py
  joplin/settings.py
  template.env
Labels: PR: unreviewed

#785 v3.4.3 master => production
  .circleci/vars/heroku_pr_vars.py
  Pipfile
  Pipfile.lock
  README.md
  joplin/base/signals/aws_publish.py
  joplin/settings.py
  template.env
Labels: PR: unreviewed

#777 4591 - add department resolver to official document pages
  joplin/api/schema.py
Labels: PR: partially-approved

#787 joplin to 3.5.0
  joplin/api/schema.py
Labels: PR: unreviewed
