Repository cityofaustin/joplin, pull requests merged in 2020-10, with the labels that each got.

#815 4897 - Remove tags from images
  joplin/base/models/translated_image.py
  joplin/pages/news_page/migrations/0003_auto_20200924_2327.py
  joplin/pages/official_documents_page/migrations/0011_auto_20200924_2327.py
  joplin/templates/wagtailimages/images/index.html
Labels: PR: reviewed-approved

#813 4947- add image to rich text information
  joplin/base/models/constants.py
  joplin/pages/information_page/models.py
Labels: PR: unreviewed

#819 joplin prod to 3.9.1
  LICENSE.txt
  Pipfile
  Pipfile.lock
  joplin/base/models/constants.py
  joplin/base/models/translated_image.py
  joplin/pages/information_page/models.py
  joplin/pages/news_page/migrations/0003_auto_20200924_2327.py
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_page/migrations/0011_auto_20200924_2327.py
  joplin/templates/wagtailimages/images/index.html
Labels: PR: unreviewed

#820 Revert the merge "joplin prod to 3.9.1"
  LICENSE.txt
  Pipfile
  Pipfile.lock
  joplin/base/models/constants.py
  joplin/base/models/translated_image.py
  joplin/pages/information_page/models.py
  joplin/pages/news_page/migrations/0003_auto_20200924_2327.py
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_page/migrations/0011_auto_20200924_2327.py
  joplin/templates/wagtailimages/images/index.html
Labels: PR: unreviewed

#821 fix bug I introduced - move comment in file
  joplin/templates/wagtailimages/images/index.html
Labels: PR: reviewed-approved

#822 Joplin prod to 3.9.2
  joplin/templates/wagtailimages/images/index.html
Labels: PR: unreviewed

#825 add top pages to HomePage model
  joplin/api/schema.py
  joplin/pages/home_page/migrations/0003_homepagetoppage.py
  joplin/pages/home_page/migrations/0004_auto_20201002_2047.py
  joplin/pages/home_page/models.py
  joplin/pages/news_page/migrations/0003_auto_20201002_2021.py
  joplin/pages/official_documents_page/migrations/0011_auto_20201002_2021.py
Labels: PR: unreviewed

#824 Issue 5032: add top pages to HomePage model
  joplin/api/schema.py
  joplin/pages/home_page/migrations/0003_homepagetoppage.py
  joplin/pages/home_page/migrations/0004_auto_20201002_2047.py
  joplin/pages/home_page/models.py
  joplin/pages/news_page/migrations/0003_auto_20201002_2021.py
  joplin/pages/official_documents_page/migrations/0011_auto_20201002_2021.py
Labels: PR: unreviewed

#767 Build for a demo
  .circleci/vars/branch_overrides.py
  joplin/api/schema.py
  joplin/base/models/translated_image.py
  joplin/pages/home_page/migrations/0003_homepagetoppage.py
  joplin/pages/home_page/migrations/0004_auto_20201002_2047.py
  joplin/pages/home_page/models.py
  joplin/pages/news_page/migrations/0003_auto_20201002_2021.py
  joplin/pages/official_documents_page/migrations/0011_auto_20201002_2021.py
Labels: PR: reviewed-approved, wip

#826 4849 filter test build + improve sync scripts
  .circleci/vars/branch_overrides.py
  scripts/sync_data.sh
Labels: PR: partially-approved

#808 4769 preview graphql
  .circleci/vars/heroku_pr_vars.py
  README.md
  joplin/api/decorators.py
  joplin/api/preview_schema.py
  joplin/api/views.py
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/base_page/models.py
  joplin/settings.py
  joplin/urls.py
  joplin/users/fixtures/__init__.py
  joplin/users/fixtures/administrative/user_for_build_process.py
  template.env
Labels: PR: reviewed-approved

#831 prod to 3.11.0
  .circleci/vars/branch_overrides.py
  .circleci/vars/heroku_pr_vars.py
  README.md
  joplin/api/decorators.py
  joplin/api/preview_schema.py
  joplin/api/views.py
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/base_page/models.py
  joplin/settings.py
  joplin/urls.py
  joplin/users/fixtures/__init__.py
  joplin/users/fixtures/administrative/user_for_build_process.py
  scripts/sync_data.sh
  template.env
Labels: PR: unreviewed

#830 Issue 5052: site_search view
  Pipfile
  Pipfile.lock
  docker-entrypoint.sh
  joplin/api/schema.py
  joplin/base/views/site_search.py
  joplin/pages/base_page/models.py
  joplin/pages/event_page/models.py
  joplin/pages/location_page/models.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/topic_page/models.py
  joplin/settings.py
  joplin/urls.py
Labels: PR: unreviewed, wip

#834 Production to master rebase
  LICENSE.txt
  Pipfile.lock
  joplin/base/models/constants.py
  joplin/pages/information_page/models.py
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_page/management/commands/extract_document_text.py
Labels: PR: unreviewed

#835 v3.12.1 master => prod
  joplin/base/views/site_search.py
Labels: PR: unreviewed
