Repository cityofaustin/joplin, pull requests merged in 2020-08, with the labels that each got.

#789 Issue 4397: new user email
  joplin/pages/base_page/models.py
  joplin/settings.py
  joplin/templates/joplin_UI/email/new_user.html
  joplin/templates/joplin_UI/email/new_user.txt
  joplin/templates/joplin_UI/email/new_user_subject.txt
  joplin/users/models.py
  joplin/users/wagtail_hooks.py
  template.env
Labels: PR: partially-approved

#791 Issue 4758: hyperlink
  joplin/pages/location_page/migrations/0003_auto_20200807_1833.py
  joplin/pages/location_page/models.py
  joplin/pages/official_documents_collection/migrations/0002_auto_20200807_1837.py
  joplin/pages/official_documents_collection/models.py
Labels: PR: reviewed-approved, wip

#790 Issue 4641: add body field to official documents
  joplin/base/translation.py
  joplin/pages/official_documents_page/migrations/0007_auto_20200807_1819.py
  joplin/pages/official_documents_page/models.py
Labels: PR: partially-approved

#793 v3.6.0 master => production
  joplin/base/translation.py
  joplin/pages/base_page/models.py
  joplin/pages/location_page/migrations/0003_auto_20200807_1833.py
  joplin/pages/location_page/models.py
  joplin/pages/official_documents_collection/migrations/0002_auto_20200807_1837.py
  joplin/pages/official_documents_collection/models.py
  joplin/pages/official_documents_page/migrations/0007_auto_20200807_1819.py
  joplin/pages/official_documents_page/models.py
  joplin/settings.py
  joplin/templates/joplin_UI/email/new_user.html
  joplin/templates/joplin_UI/email/new_user.txt
  joplin/templates/joplin_UI/email/new_user_subject.txt
  joplin/users/models.py
  joplin/users/wagtail_hooks.py
  template.env
Labels: PR: unreviewed

#795 prod to 3.7.0
  joplin/api/schema.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/pages/department_page/models.py
  joplin/pages/news_page/models.py
Labels: PR: unreviewed

#796 Issue 4375 (2nd attempt): update pipenv and package.json dependencies
  .gitignore
  Pipfile
  Pipfile.lock
  joplin/css/editor.scss
  joplin/groups/factories.py
  joplin/package.json
  joplin/pages/department_page/tests.py
  joplin/pages/home_page/fixtures/administrative/root_home_page.py
  joplin/pages/official_documents_page/migrations/0008_auto_20200811_2012.py
  joplin/settings.py
  joplin/templates/wagtailadmin/login.html
  joplin/webpack.build.js
  joplin/yarn.lock
  yarn.lock
Labels: PR: unreviewed

#797 Issue 4695: Automate Translation Report sending
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/management/commands/send_translation_report.py
  joplin/groups/fixtures/__init__.py
  joplin/groups/fixtures/administrative/group_permissions.py
  joplin/groups/fixtures/administrative/translators.py
  joplin/pages/official_documents_page/migrations/0008_auto_20200813_2036.py
  joplin/templates/joplin_UI/reports/pages_to_translate.html
  joplin/templates/joplin_UI/reports/pages_to_translate.txt
  joplin/templates/wagtailusers/users/create.html
  joplin/templates/wagtailusers/users/edit.html
  joplin/users/fixtures/administrative/editor_for_test_env.py
  joplin/users/forms.py
  joplin/users/js/index.js
  joplin/users/templatetags/user_tags.py
Labels: PR: unreviewed

#798 v3.7.1 master => production
  .gitignore
  Pipfile
  Pipfile.lock
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/management/commands/send_translation_report.py
  joplin/css/editor.scss
  joplin/groups/factories.py
  joplin/groups/fixtures/__init__.py
  joplin/groups/fixtures/administrative/group_permissions.py
  joplin/groups/fixtures/administrative/translators.py
  joplin/package.json
  joplin/pages/department_page/tests.py
  joplin/pages/home_page/fixtures/administrative/root_home_page.py
  joplin/pages/official_documents_page/migrations/0008_auto_20200811_2012.py
  joplin/settings.py
  joplin/templates/joplin_UI/reports/pages_to_translate.html
  joplin/templates/joplin_UI/reports/pages_to_translate.txt
  joplin/templates/wagtailadmin/login.html
  joplin/templates/wagtailusers/users/create.html
  joplin/templates/wagtailusers/users/edit.html
  joplin/users/fixtures/administrative/editor_for_test_env.py
  joplin/users/forms.py
  joplin/users/js/index.js
  joplin/users/templatetags/user_tags.py
  joplin/webpack.build.js
  joplin/yarn.lock
  yarn.lock
Labels: PR: unreviewed

#800 testing circleci breaking
  .circleci/config.yml
  .circleci/docker/joplin-ci-test.Dockerfile
Labels: PR: unreviewed

#804 use exact match to check heroku app existence
  .circleci/scripts/helpers.sh
Labels: PR: unreviewed

#801 4872 - Add link to Official Documents summary field
  Pipfile
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_page/migrations/0009_auto_20200827_1552.py
  joplin/pages/official_documents_page/models.py
Labels: PR: unreviewed
