Repository cityofaustin/joplin, pull requests merged in 2020-06, with the labels that each got.

#737 until we get localized urls working just send over the english slug
  joplin/api/schema.py
Labels: PR: partially-approved

#738 Master -> prod v3.2.3
  joplin/api/schema.py
  joplin/pages/base_page/models.py
  joplin/pages/information_page/models.py
  joplin/users/fixtures/__init__.py
  joplin/users/fixtures/administrative/editor_for_test_env.py
  joplin/users/fixtures/helpers/create_fixture.py
  joplin/users/tests/conftest.py
  joplin/users/tests/tests.py
Labels: PR: unreviewed

#734 4097 permissions search view
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/views/joplin_search_views.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/wagtail_hooks.py
  joplin/groups/fixtures/helpers/create_fixture.py
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/users/tests/tests.py
Labels: PR: partially-approved

#741 prod to 3.2.4
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/views/joplin_search_views.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/wagtail_hooks.py
  joplin/groups/fixtures/helpers/create_fixture.py
  joplin/pages/service_page/factories.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/users/tests/tests.py
Labels: PR: unreviewed

#739 4099 perm edit view
  .circleci/config.yml
  .circleci/docker/joplin-ci-test.Dockerfile
  joplin/base/views/new_page_from_modal.py
  joplin/base/wagtail_hooks.py
  joplin/pages/base_page/migrations/0002_add_pageviewpermissions.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/settings.py
  joplin/templates/wagtailadmin/pages/listing/_page_title_explore.html
  joplin/users/tests/tests.py
Labels: PR: partially-approved, wip

#743 prod to 3.2.5
  .circleci/config.yml
  .circleci/docker/joplin-ci-test.Dockerfile
  joplin/base/views/new_page_from_modal.py
  joplin/base/wagtail_hooks.py
  joplin/pages/base_page/migrations/0002_add_pageviewpermissions.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/settings.py
  joplin/templates/wagtailadmin/pages/listing/_page_title_explore.html
  joplin/users/tests/tests.py
Labels: PR: unreviewed

#745 prod to 3.2.6
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/templatetags/joplin_tags.py
  joplin/db/fixtures/group_permissions_settings.json
  joplin/db/fixtures/themes.json
  joplin/groups/fixtures/helpers/group_permissions.py
  joplin/js/CreateContentModal/index.js
  joplin/snippets/theme/fixtures/__init__.py
  joplin/snippets/theme/fixtures/test_cases/janis_themes.py
  joplin/users/fixtures/administrative/editor_for_test_env.py
Labels: PR: unreviewed

#746 4400 Prevent editors/authors from creating topics and topic collections
  joplin/base/templatetags/joplin_tags.py
  joplin/conftest.py
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/js/CreateContentModal/index.js
  joplin/templates/wagtailadmin/pages/search_header.html
Labels: PR: unreviewed

#748 prod to 3.2.7
  joplin/base/templatetags/joplin_tags.py
  joplin/conftest.py
  joplin/js/CreateContentModal/ChooseTypeStep.js
  joplin/js/CreateContentModal/index.js
  joplin/templates/wagtailadmin/pages/search_header.html
Labels: PR: unreviewed

#750 4356 queue banner
  .circleci/vars/branch_overrides.py
  joplin/base/signals/janis_build_triggers.py
  joplin/css/pages/edit.scss
  joplin/joplin_UI/pageStatus.scss
  joplin/settings.py
  joplin/templates/joplin_UI/pageStatus/publishing_modal.html
  joplin/templates/joplin_UI/pageStatus/unpublishing_modal.html
  joplin/templates/wagtailadmin/pages/edit.html
Labels: PR: unreviewed

#744 Issue 4356: publish queue notification
  .circleci/scripts/build_heroku_infrastructure.sh
  .circleci/vars/branch_overrides.py
  Pipfile
  Pipfile.lock
  README.md
  README/testing.md
  joplin/base/apps.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/signals/janis_build_triggers.py
  joplin/base/signals/netlify_publish.py
  joplin/base/signals/publish_v3.py
  joplin/base/templatetags/joplin_tags.py
  joplin/base/tests/test_incremental_builds.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/views/publish_succeeded.py
  joplin/conftest.py
  joplin/css/editor.scss
  joplin/css/pages/edit.scss
  joplin/css/variables.scss
  joplin/importer/__init__.py
  joplin/joplin_UI/messages.scss
  joplin/joplin_UI/pageStatus.scss
  joplin/js/pageStatus/index.js
  joplin/package.json
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/base_page/migrations/0003_add_publish_fields.py
  joplin/pages/base_page/models.py
  joplin/pages/base_page/tests/test_status_string.py
  joplin/pages/base_page/tests/tests.py
  joplin/pages/department_page/fixtures/helpers/components.py
  joplin/pages/department_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/location_page/fixtures/test_cases/live_city_hall.py
  joplin/pages/location_page/fixtures/test_cases/live_library.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH_written_for_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_CPIO_written_for_APH.py
  joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/topic_collection_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/topic_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/topic_page/fixtures/test_cases/title.py
  joplin/settings.py
  joplin/snippets/theme/fixtures/helpers/create_fixture.py
  joplin/templates/__init__.py
  joplin/templates/joplin_UI/messages/publishing.html
  joplin/templates/joplin_UI/messages/unpublishing.html
  joplin/templates/joplin_UI/pageStatus/publishing_modal.html
  joplin/templates/joplin_UI/pageStatus/unpublishing_modal.html
  joplin/templates/wagtailadmin/base.html
  joplin/templates/wagtailadmin/pages/edit.html
  joplin/templates/wagtailadmin/shared/page_status_tag.html
  joplin/urls.py
  joplin/webpack.base.js
  joplin/webpack.build.js
  joplin/webpack.dev.js
  joplin/yarn.lock
  scripts/load_from_heroku.sh
  setup.cfg
Labels: PR: unreviewed

#751 v3.2.8 master => production
  .circleci/scripts/build_heroku_infrastructure.sh
  .circleci/vars/branch_overrides.py
  Pipfile
  Pipfile.lock
  README.md
  README/testing.md
  joplin/base/apps.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/signals/janis_build_triggers.py
  joplin/base/signals/netlify_publish.py
  joplin/base/signals/publish_v3.py
  joplin/base/templatetags/joplin_tags.py
  joplin/base/tests/test_incremental_builds.py
  joplin/base/views/new_page_from_modal.py
  joplin/base/views/publish_succeeded.py
  joplin/conftest.py
  joplin/css/editor.scss
  joplin/css/pages/edit.scss
  joplin/css/variables.scss
  joplin/importer/__init__.py
  joplin/joplin_UI/messages.scss
  joplin/joplin_UI/pageStatus.scss
  joplin/js/pageStatus/index.js
  joplin/package.json
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/fixtures/helpers/page_type_map.py
  joplin/pages/base_page/migrations/0003_add_publish_fields.py
  joplin/pages/base_page/models.py
  joplin/pages/base_page/tests/test_status_string.py
  joplin/pages/base_page/tests/tests.py
  joplin/pages/department_page/fixtures/helpers/components.py
  joplin/pages/department_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/location_page/fixtures/test_cases/live_city_hall.py
  joplin/pages/location_page/fixtures/test_cases/live_library.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_APH_written_for_APH.py
  joplin/pages/news_page/fixtures/test_cases/written_by_CPIO_written_for_APH.py
  joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/service_page/fixtures/helpers/components.py
  joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/topic_collection_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/topic_page/fixtures/test_cases/kitchen_sink.py
  joplin/pages/topic_page/fixtures/test_cases/title.py
  joplin/settings.py
  joplin/snippets/theme/fixtures/helpers/create_fixture.py
  joplin/templates/__init__.py
  joplin/templates/joplin_UI/messages/publishing.html
  joplin/templates/joplin_UI/messages/unpublishing.html
  joplin/templates/joplin_UI/pageStatus/publishing_modal.html
  joplin/templates/joplin_UI/pageStatus/unpublishing_modal.html
  joplin/templates/wagtailadmin/base.html
  joplin/templates/wagtailadmin/pages/edit.html
  joplin/templates/wagtailadmin/shared/page_status_tag.html
  joplin/urls.py
  joplin/webpack.base.js
  joplin/webpack.build.js
  joplin/webpack.dev.js
  joplin/yarn.lock
  scripts/load_from_heroku.sh
  setup.cfg
Labels: PR: unreviewed

#752 improve template.env documentation; upgrade to postgres v12
  .circleci/vars/heroku_pr_vars.py
  docker-compose.yml
  joplin/settings.py
  scripts/make_pycharm_vars.py
  template.env
Labels: PR: partially-approved

#753 v3.2.9 master => prod
  .circleci/vars/heroku_pr_vars.py
  docker-compose.yml
  joplin/settings.py
  scripts/make_pycharm_vars.py
  template.env
Labels: PR: unreviewed

#754 Issue 4561: fix unpublishing UX bugs
  joplin/templates/joplin_UI/messages/unpublishing.html
  joplin/templates/wagtailadmin/pages/confirm_unpublish.html
Labels: PR: partially-approved

#757 v3.2.10 master => production
  joplin/templates/joplin_UI/messages/unpublishing.html
  joplin/templates/wagtailadmin/pages/confirm_unpublish.html
Labels: PR: unreviewed

#756 Issue 4495: make a translation report
  .idea/runConfigurations/Undocked_Joplin.xml
  joplin/base/management/commands/make_translation_report.py
  joplin/templates/joplin_UI/reports/pages_to_translate.html
  scripts/make_pycharm_vars.py
  template.env
Labels: PR: partially-approved

#758 v3.2.11 master => production
  .idea/runConfigurations/Undocked_Joplin.xml
  joplin/base/management/commands/make_translation_report.py
  joplin/templates/joplin_UI/reports/pages_to_translate.html
  scripts/make_pycharm_vars.py
  template.env
Labels: PR: unreviewed

#760 fix inconsistent revision publish statuses
  joplin/base/views/publish_succeeded.py
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/models.py
Labels: PR: partially-approved

#761 v3.2.12 master => prod
  joplin/base/views/publish_succeeded.py
  joplin/pages/base_page/fixtures/helpers/create_fixture_map.py
  joplin/pages/base_page/models.py
Labels: PR: unreviewed
