Repository cityofaustin/joplin, pull requests merged in 2020-09, with the labels that each got.

#806 prod to 3.8.0
  .circleci/config.yml
  .circleci/docker/joplin-ci-test.Dockerfile
  .circleci/scripts/helpers.sh
  Pipfile
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_page/migrations/0009_auto_20200827_1552.py
  joplin/pages/official_documents_page/models.py
Labels: PR: unreviewed

#807 4771 docs
  Pipfile
  Pipfile.lock
  joplin/pages/official_documents_page/management/commands/extract_document_text.py
Labels: PR: unreviewed

#810 prod to 3.8.1
  Pipfile
  Pipfile.lock
  joplin/pages/official_documents_page/management/commands/extract_document_text.py
Labels: PR: unreviewed

#809 Issue 4776: implement searchIndex for Elasticsearch
  joplin/api/schema.py
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/official_documents_page/migrations/0009_auto_20200909_1529.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_collection_page/models.py
Labels: PR: partially-approved

#811 v3.9.0 master => prod
  joplin/api/schema.py
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/official_documents_page/migrations/0009_auto_20200909_1529.py
  joplin/pages/official_documents_page/migrations/0010_merge_20200914_2007.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_collection_page/models.py
Labels: PR: unreviewed

#812 4720 change copy on news page help text
  joplin/pages/news_page/models.py
Labels: PR: reviewed-approved

#817 Update demo site
  .circleci/config.yml
  .circleci/docker/joplin-ci-test.Dockerfile
  .circleci/scripts/helpers.sh
  .gitignore
  LICENSE.txt
  Pipfile
  Pipfile.lock
  joplin/api/schema.py
  joplin/base/fixtures/administrative/mandatory_fixtures.py
  joplin/base/management/commands/load_joplin_data.py
  joplin/base/management/commands/send_translation_report.py
  joplin/base/translation.py
  joplin/css/editor.scss
  joplin/groups/factories.py
  joplin/groups/fixtures/__init__.py
  joplin/groups/fixtures/administrative/group_permissions.py
  joplin/groups/fixtures/administrative/translators.py
  joplin/package.json
  joplin/pages/base_page/models.py
  joplin/pages/department_page/models.py
  joplin/pages/department_page/tests.py
  joplin/pages/home_page/fixtures/administrative/root_home_page.py
  joplin/pages/location_page/migrations/0003_auto_20200807_1833.py
  joplin/pages/location_page/models.py
  joplin/pages/news_page/models.py
  joplin/pages/official_documents_collection/migrations/0002_auto_20200807_1837.py
  joplin/pages/official_documents_collection/models.py
  joplin/pages/official_documents_page/management/commands/extract_document_text.py
  joplin/pages/official_documents_page/migrations/0007_auto_20200807_1819.py
  joplin/pages/official_documents_page/migrations/0008_auto_20200811_2012.py
  joplin/pages/official_documents_page/migrations/0009_auto_20200827_1552.py
  joplin/pages/official_documents_page/migrations/0009_auto_20200909_1529.py
  joplin/pages/official_documents_page/migrations/0010_merge_20200914_2007.py
  joplin/pages/official_documents_page/models.py
  joplin/pages/service_page/models.py
  joplin/pages/topic_collection_page/models.py
  joplin/settings.py
  joplin/templates/joplin_UI/email/new_user.html
  joplin/templates/joplin_UI/email/new_user.txt
  joplin/templates/joplin_UI/email/new_user_subject.txt
  joplin/templates/joplin_UI/reports/pages_to_translate.html
  joplin/templates/joplin_UI/reports/pages_to_translate.txt
  joplin/templates/wagtailadmin/login.html
  joplin/templates/wagtailusers/users/create.html
  joplin/templates/wagtailusers/users/edit.html
  joplin/users/fixtures/administrative/editor_for_test_env.py
  joplin/users/forms.py
  joplin/users/js/index.js
  joplin/users/models.py
  joplin/users/templatetags/user_tags.py
  joplin/users/wagtail_hooks.py
  joplin/webpack.build.js
  joplin/yarn.lock
  template.env
  yarn.lock
Labels: PR: unreviewed
